config/routes.rb
Rails.application.routes.draw do
  resources :wikis do
    resources :collaborators, only: [:index, :create, :destroy]
  end
  
  resources :charges, only: [:new, :create]
  
  devise_for :users
  
  get 'welcome/about'
  
  get 'charges/downgrade', as: 'downgrade'

  root 'welcome#index'

end

app/models/amount.rb
class Amount < ActiveRecord::Base
    def self.default
        7_99 # should return $7.99 as the amount to charge
    end
end

app/models/collaborator.rb
class Collaborator < ActiveRecord::Base
  belongs_to :user
  belongs_to :wiki
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable, :confirmable,
         :recoverable, :rememberable, :trackable, :validatable
         
  has_many :wikis
  before_save { self.role ||= :standard }

  attr_accessor :login
  validates_format_of :username, with: /^[a-zA-Z0-9_\.]*$/, :multiline => true
  validate :validate_username
  
  enum role: [:standard, :premium, :admin]
  
  def validate_username
    if User.where(email: username).exists?
      errors.add(:username, :invalid)
    end
  end
  
  def self.find_for_database_authentication(warden_conditions)
    conditions = warden_conditions.dup
    if login = conditions.delete(:login)
      where(conditions.to_hash).where(["username = :value OR lower(email) = :value", { :value => login.downcase }]).first
    elsif conditions.has_key?(:username) || conditions.has_key?(:email)
      conditions[:email].downcase! if conditions[:email]
      where(conditions.to_hash).first
    end
  end
end

app/models/wiki.rb
class Wiki < ActiveRecord::Base
  belongs_to :user
  has_many :collaborators
  has_many :users, through: :collaborators
  before_save { self.private ||= 'false'}
  
  def collaborator_for(user)
    collaborators.find_by(user_id: user.id)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  
  include Pundit
  
  rescue_from Pundit::NotAuthorizedError, with: :user_not_authorized
  
  before_action :configure_permitted_parameters, if: :devise_controller?
  before_action :authenticate_user!
  
  private
  
  def user_not_authorized(exception)
    policy_name = exception.policy.class.to_s.underscore
    
    flash[:alert] = t "#{policy_name}.#{exception.query}", scope: "pundit", default: :default
    redirect_to(request.referrer || root_path)
  end
  
  protected
  
  def configure_permitted_parameters
    added_attr = [:username, :email, :password, :password_confirmation, :remember_me]
    devise_parameter_sanitizer.permit :sign_up, keys: added_attr
    devise_parameter_sanitizer.permit :account_update, keys: added_attr
  end
end

app/controllers/charges_controller.rb
class ChargesController < ApplicationController
    def create
        customer = Stripe::Customer.create(
            email: current_user.email,
            card: params[:stripeToken]
        )
        
        charge = Stripe::Charge.create(
            customer: customer.id,
            amount: Amount.default,
            description: "Premium Subscription - #{current_user.email}",
            currency: 'usd'
        )
        
        current_user.premium!
        
        flash[:notice] = "Thank you for your subscription! You may now reap the benifits that your Premium status has to offer!"
        
        redirect_to root_path
        
        rescue Stripe::CardError => e
            flash[:alert] = e.message
            redirect_to new_charge_path
    end
    
    def new
        unless current_user.admin?
            @stripe_btn_data = {
                key: "#{Rails.configuration.stripe[:publishable_key] }",
                description: "Premium Subscription - #{current_user.email}",
                amount: Amount.default
            }
        else           
            flash[:alert] = "As an admin you are granted full permissions, there is no need to upgrade."
            redirect_to root_path
        end
    end
    
    def downgrade
        if current_user.premium?
            current_user.standard!
            
            Wiki.where(user_id: current_user.id).update_all(private: 'false')
            
            flash[:notice] = "Your account has successfully been downgraded. We are glad to have been able to help you with this."
        elsif current_user.admin?
            flash[:alert] = "As an admin you are granted full permissions, and downgrading is not posible."
        else
            flash[:alert] = "Sorry, that action cannot be completed with your current membership status."
        end
        redirect_to root_path
    end
end

app/controllers/collaborators_controller.rb
class CollaboratorsController < ApplicationController
  before_action :set_wiki
  
  def index
    @users = User.all
    authorize @wiki.collaborators.new(user_id: params[:user_id])
  end
  
  def create
    @collaborator = @wiki.collaborators.new(user_id: params[:user_id])
    
    authorize @collaborator
    if @collaborator.save
      flash[:notice] = "#{@collaborator.user.username} was added as a collaborator."
    else
      flash[:alert] = "There was a problem while saving a new collaborator. Please try again."
    end
    redirect_to wiki_collaborators_path(@wiki)
  end
  
  def destroy
    @collaborator = @wiki.collaborators.find(params[:id])
    
    authorize @collaborator
    if @collaborator.destroy
      flash[:notice] = "#{@collaborator.user.username} was removed from being a collaborator."
    else
      flash[:alert] = "There was a problem removing a collaborator. Please try again."
    end
    redirect_to wiki_collaborators_path(@wiki)
  end
  
  private
  
  def set_wiki
    @wiki = Wiki.find(params[:wiki_id])
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  skip_before_action :authenticate_user!
  def index
  end

  def about
  end
end

app/controllers/wikis_controller.rb
class WikisController < ApplicationController
    before_action :get_wiki_by_id, only: [:show, :edit, :update, :destroy]
    
    def index
        @wikis = policy_scope(Wiki)
        authorize Wiki    
    end
    
    def show
        authorize @wiki
    end
    
    def new
        @wiki = Wiki.new
        authorize @wiki
    end
    
    def create
        @wiki = Wiki.new(wiki_params)
        @wiki.user = current_user
        
        authorize @wiki
        if @wiki.save
            flash[:notice] = "Wiki was saved."
            redirect_to [@wiki]
        else
            flash.now[:alert] = "There was an error saving the wiki. Please try again."
            render :new
        end
    end
    
    def edit
        authorize @wiki
    end
    
    def update
        @wiki.assign_attributes(wiki_params)
        authorize @wiki
        
        if @wiki.save
            flash[:notice] = "Wiki successfully updated!"
            redirect_to @wiki 
        else
            flash.now[:alert] = "There was an error saving your changes. Please try again."
            render :edit
        end
    end
    
    def destroy
        authorize @wiki
        if @wiki.destroy
            flash[:notice] = "Wiki successfully deleted."
            redirect_to wikis_path
        else
            flash.now[:alert] = "There was an error deleting the post."
            render :show
        end
    end
    
    private
    
    def wiki_params
        params.require(:wiki).permit(:title, :body, :private)
    end
    
    def get_wiki_by_id
        @wiki = Wiki.find(params[:id])
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/charges_helper.rb
module ChargesHelper
    def render_charge_button
        @stripe_btn_data = {
            key: "#{Rails.configuration.stripe[:publishable_key] }",
            description: "Premium Subscription - #{current_user.email}",
            amount: Amount.default
        }
        "<script class='stripe-button profile-link' src='https://checkout.stripe.com/checkout.js' data-key='#{@stripe_btn_data[:key]}' data-amount='#{@stripe_btn_data[:amount]}' data-description='#{@stripe_btn_data[:description]}'></script>".html_safe
    end
end

app/helpers/collaborators_helper.rb
module CollaboratorsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/helpers/wikis_helper.rb
module WikisHelper
end

app/views/charges/_confirm_downgrade.html.erb
<br>
<div class="jumbotron">
    <h2>You are currently a Premium member.</h2>
    <p>This gives you access to private wikis.</p>
    <p>Would you  like to downgrade your account to standard?</p>
    <small>Downgrading will cause all your wikis to become public.</small>
    <br></br>
    <p>
        <%= link_to "Yes, Downgrade me", downgrade_path, :class => 'btn btn-danger', data: { confirm: "Are you sure? This action cannot be undone." }  %>
        <%= link_to "Nope!", root_path, :class => 'btn btn-success'  %>
    </p>
</div>

app/views/charges/new.html.erb
<% if current_user.premium? %>
    <%= render partial: 'confirm_downgrade' %>
<% else %>
    <%= form_tag charges_path do %>
        <br>
        <div class="jumbotron">
            <h2>You are currently a standard member.</h2>
            <p>To gain access to private wikis you must upgrade your account.</p>
            <p>For just $7.99 you can upgrade to <strong><i>Premium!</i></strong> Would you  like to?</p>
            <script class='stripe-button' src="https://checkout.stripe.com/checkout.js" data-key="<%= @stripe_btn_data[:key] %>" data-amount="<%= @stripe_btn_data[:amount] %>" data-description="<%= @stripe_btn_data[:description] %>"></script>
            <%= link_to "Not right now.", root_path, :class => 'btn'  %>        
        </div>
    <% end %> 
<% end %>

app/views/collaborators/index.html.erb
<h4>Manage Collaborators for:</h4>
<h2><%= $markdown.render(@wiki.title).html_safe %></h2>

<table class="table">
    <thead>
        <th>User</th>
        <th></th>
    </thead>
    <tbody>
        <% @users.each do |user| %>
            <% unless user == @wiki.user %>
                <tr>
                    <td><%= user.username %></td>
                    <td>
                        <% if @wiki.users.include?(user) %>
                            <%= link_to "Remove as Collaborator", [@wiki, @wiki.collaborator_for(user)], method: :delete, class: "btn btn-danger" %>
                        <% else %>
                            <%= link_to "Add as Collaborator", wiki_collaborators_path(@wiki, user_id: user.id), method: :post, class: "btn btn-success" %>
                        <% end %>
                    </td>
                </tr>
            <% end %>
        <% end %>
    </tbody>
</table>

app/views/layouts/_role_icon.html.erb
<% if current_user.admin? %>
    Signed in as: 
    <small><i>admin</i></small>
<% end %>
<% if current_user.premium? %>
    Signed in as: 
    <%= link_to image_tag("premium-icon.png", size: "21", alt: "Premium"), new_charge_path %>
<% end %>
<% if current_user.standard? %>
    <% unless request.env['PATH_INFO'] == new_charge_path %>
        <%= link_to 'Upgrade', new_charge_path, :class => 'navbar-link upgrade-btn' %>
    <% end %>
    Signed in as: 
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Interstellar Wiki</title>
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <div class="container">
    <ul class="nav nav-tabs">
      <li><%= link_to "Home", root_path %></li>
      <li><%= link_to "About", welcome_about_path %></li>
      <li><%= link_to "Wikis", wikis_path %></li>
      
      <div class="user-ctrl">
        <% if user_signed_in? %>
          <%= render 'layouts/role_icon' %>
          <%= current_user.username %> | 
          <%= link_to 'Edit profile', edit_user_registration_path, :class => 'navbar-link' %> - 
          <%= link_to "Sign Out", destroy_user_session_path, method: :delete, :class => 'navbar-link'  %>
        <% else %>
          <%= link_to "Sign Up", new_user_registration_path, :class => 'navbar-link'  %> -
          <%= link_to "Sign In", new_user_session_path, :class => 'navbar-link'  %>
        <% end %>
      </div>
    </ul>
    
    <% if flash[:notice] %>
      <div class="alert alert-success">
        <button type="button" class="close" data-dismiss="alert">&times;</button>
        <%= flash[:notice] %>
      </div>
    <% elsif flash[:alert] %>
      <div class="alert alert-warning">
        <button type="button" class="close" data-dismiss="alert">&times;</button>
        <%= flash[:alert] %>
      </div>
    <% end %>
    
    <%= yield %>
  </div>
</body>
</html>

app/views/welcome/about.html.erb
<h1 class="page-header">About Us</h1><br>
<h3>Welcome to the ultimate wiki-powered guide to exploring the universe!</h3>
<h4>At the current pace technology is racing, we are quite literly reaching for the stars!</h4>
<h6>The goal of this <i>Wiki</i> is to provide all the information you might need to assist you in your journeys.</h6> 

<p>Some of the catogories that this <i>Wiki</i> aims to cover:</p>
<ul>
    <li>List of all known galaxies.</li>
    <li>List of all known stars.</li>
    <li>List of all known planets.</li>
    <li>List of all known life-forms.</li>
    <li>List of all known space-faring Gov'ts/Corps./Orgs.</li>
    <li>Notable personalities related to the exloration/discovery of the universe.</li>
    <li>Notable events related to the exloration/discovery of the universe.</li>
</ul>

<p>As of 3/1/2017AD (by the gregarian calender) Space travel is essentially non-existant...
However, much research/developmment is underway, to make this dream a reality.

InterstellarWiki aims to become a part of this <i>new frontier</i> by providing a central 
collection of all known data relating to Space Travel.</p>

app/views/welcome/index.html.erb
<br>
<div class="jumbotron">
    <h1>Interstellar Wiki</h1>
    <p>Your guide to exploring the Stars! (and beyond?)</p>
    <p>
        <%= link_to "Sign In", new_user_session_path, :class => 'navbar-link'  %> or
        <%= link_to "Sign Up", new_user_registration_path, :class => 'navbar-link'  %> today!
    </p>
</div>

<div class="row">
    <div class="col-md-4">
        <h2>Browse our selection of user provided content</h2>
        <p>WikiStellar contains a rich library of everything you need to know about the cosmos.</p>
    </div>    
    <div class="col-md-4">
        <h2>Join the community</h2>
        <p><%= link_to "Sign Up", new_user_registration_path, :class => 'navbar-link'  %> today and help add to Wikistellar.</p>
    </div>    
    <div class="col-md-4">
        <h2>Explore</h2>
        <p>Discover how the various wiki pages interact to create a web of informative data.</p>
    </div>
</div>

app/views/wikis/_form.html.erb
<%= form_for [wiki] do |f| %>
    <div class="form-group">
        <%= f.label :title %>
        <%= f.text_field :title, class: 'form-control', placeholder: "Enter wiki title" %>
    </div>    
    <div class="form-group">
        <%= f.label :body %>
        <%= f.text_area :body, rows: 12, class: 'form-control', placeholder: "Enter post body" %>
    </div> 
    <% unless current_user.standard? %>
        <div class="new-wiki-private-check-box form-group">
            <%= f.label :private, class: 'checkbox' do %>
                <%= f.check_box :private %> Check box if this Wiki is private?
            <% end %>
        </div>    
    <% end %> 
    <div class="form-group">
        <%= f.submit "Save", class: 'btn btn-success' %>
    </div>
<% end %>

app/views/wikis/_index.html.erb
<% wikis.each do |wiki| %>
    <%= render partial: 'privacy_icon', locals: {wiki: wiki} %>
    <%= link_to $markdown.render(wiki.title).html_safe, wiki %>
<% end %>

app/views/wikis/_privacy_icon.html.erb
<% if wiki.private? %>
    <%= image_tag 'white-key.png', size: '21x14', alt: 'private', class: 'lock-key-icon' %>
<% else %>
    <%= image_tag 'open-door.png', size: '14x21', alt: ' public', class: 'open-door-icon' %>
<% end %>

app/views/wikis/edit.html.erb
<h1>Edit Wiki</h1>

<div class="row">
    <div class="col-md-4">
        <p>Thank you for contributing to Interstellar Wiki! Here are some guidelines:</p>
        <ul>
            <li>Wikis will be nested by arch-topics.</li>            <!-- to do: create these arch-topics and nest wikis within them, as well as display in wiki/index.-->
            <li>Please try and source all claims.</li>
            <li>See the styleguide page, for more info.</li>         <!-- to do: create a styleguide page outlining the vision of interstellar wiki pages. -->
        </ul>
    </div>
    <div class="col-md-8">
        <%= render partial: 'form', locals: { wiki: @wiki } %>
    </div>
</div>
<% if @wiki.private && (current_user.admin? || current_user == @wiki.user) %>
    <%= link_to "Manage Collaborators", wiki_collaborators_path(@wiki) %>
<% elsif @wiki.private && @wiki.users.include?(current_user) %>
    <%= link_to "View Collaborators", wiki_collaborators_path(@wiki) %>
<% end %>

app/views/wikis/index.html.erb
<div class="page-header">
    <% if policy(Wiki).new? %>
        <div class="pull-right">
            <%= link_to "New Wiki", new_wiki_path, class: 'btn btn-success' %>
        </div>
    <% end %>
    <h3> Browse the collection.</h3>
</div>

<div class="row">
    <div class="col-md-8 index-links">
        <%= render partial: 'index', locals: { wikis: @wikis } %>
    </div>
</div>

app/views/wikis/new.html.erb
<h1>New Wiki</h1>

<div class="row">
    <div class="col-md-4">
        <p>Thank you for contributing to Interstellar Wiki! Here are some guidelines:</p>
        <ul>
            <li>Wikis will be nested by arch-topics.</li>            <!-- to do: create these arch-topics and nest wikis within them, as well as display in wiki/index.-->
            <li>Please try and source all claims.</li>
            <li>See the styleguide page, for more info.</li>         <!-- to do: create a styleguide page outlining the vision of interstellar wiki pages. -->
        </ul>
    </div>
    <div class="col-md-8">
        <%= render partial: 'form', locals: { wiki: @wiki } %>
    </div>
</div>

app/views/wikis/show.html.erb
<div class="page-header">
    <h1><%= $markdown.render(@wiki.title).html_safe %></h1>
    <%= render partial: 'privacy_icon', locals: {wiki: @wiki} %>
    <small>
        originally created <%= time_ago_in_words(@wiki.created_at) %> ago by <%= @wiki.user.username %>
    </small>
    
</div>
<div class="row">
    <div class="col-md-8">   
        <%= $markdown.render(@wiki.body).html_safe %>
    </div>
    <div class="col-md-4">
        <% if policy(@wiki).edit? %>
            <%= link_to "Edit Wiki", edit_wiki_path(@wiki), class: 'btn btn-success' %>
        <% end %>
        <% if policy(@wiki).destroy?  %>
            <%= link_to "Delete Wiki", @wiki, method: :delete, class: 'btn btn-danger', data: {confirm: "Are you sure you want to delete this wiki? This action cannot be undone."} %>
        <% end %>
    </div>
</div>